-- Ligi
INSERT INTO Liga VALUES(1, "Bundesliga", "Niemcy", 'Leagues/Bundesliga/LOGO - Bundesliga.png');
INSERT INTO Liga VALUES(2, "BBVA", "Hiszpania", 'Leagues/BBVA/LOGO - BBVA.png');
INSERT INTO Liga VALUES(3, "Ligue 1", "Francja", 'Leagues/Ligue 1/LOGO - Ligue 1.png');
INSERT INTO Liga VALUES(4, "Premier League", "Anglia", 'Leagues/Premier League/LOGO - Premier League.png');
INSERT INTO Liga VALUES(5, "Serie A", "Włochy", 'Leagues/Serie A/LOGO - Serie A.png');

-- Stadiony
INSERT INTO Stadion VALUES(1, "Signal Iduna Park", "81359", "1974", NULL);

-- Kluby

--  Bundesliga
INSERT INTO Klub VALUES(NULL, 'Augsburg', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Bayer Leverkusen', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Bayern Munich', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Borussia Bortmund', 1, 1, NULL, 'Thomas Tuchel');
INSERT INTO Klub VALUES(NULL, 'Borussia Monchengldbach', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Bremen', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Darmstadt', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Fc Köln', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Frankfurt', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Hamburger SV', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Hannover 96', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Hetha Berlin', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Hoffenheim', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Ingolstadt', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Mainz', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Schalke', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Stuttgart', 1, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Wolfsburg', 1, NULL, NULL, NULL);

--  BBVA
INSERT INTO Klub VALUES(NULL, 'Athletic Bilbao', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Athletic Madryt', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Barcelona', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Betis', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Celta Vigo', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Eibar', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Espanyol', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Getafe', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Gijon', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Granada', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'La Coruna', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Las Palmas', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Levante', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Malaga', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Real Madryt', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Real Sociedad', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Sevilla', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Valencia', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Vallecano', 2, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Villarreal', 2, NULL, NULL, NULL);

--  Ligue 1
INSERT INTO Klub VALUES(NULL, 'Angers', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Bastia', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Bordeaux', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Caen', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'GFC Ajaccio', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Guingamp', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Lille', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Lorient', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Lyon', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Marseille', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Monaco', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Montpellier', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Nantes', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Nice', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'PSG', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Reims', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Rennes', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'St. Etienne', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Toulouse', 3, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Troyes', 3, NULL, NULL, NULL);

--  Premiere League
INSERT INTO Klub VALUES(NULL, 'Arsenal', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Aston Villa', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Bournemouth', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Chelsea', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Crystal Palace', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Everton', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Leicester City', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Liverpool', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Manchester City', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Manchester United', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Newcastle', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Norwich', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Southampton', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Stoke', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Sunderland', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Swansea', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Tottenham', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Watford', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'West Brom', 4, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'West Ham', 4, NULL, NULL, NULL);

--  Serie A
INSERT INTO Klub VALUES(NULL, 'AC Milan', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'AS Roma', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Atalanta', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Bologna', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Carpi', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Chievo', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Empoli', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Fiorentina', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Frosinone', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Genoa', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Inter', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Juventus', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Lazio', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Napoli', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Palermo', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Sampdoria', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Sassuolo', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Torino', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Udinese', 5, NULL, NULL, NULL);
INSERT INTO Klub VALUES(NULL, 'Verona', 5, NULL, NULL, NULL);

-- Zawodnicy
INSERT INTO Zawodnik VALUES(NULL, 'Pierre-Emerick', 'Aubameyang', 4, 'Napastnik', 185, 17, NULL,'Gabon');

-- Terminarz

-- Kartki

-- Gole